# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160309_1348'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_db',
        ),
    ]
