# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_medicalprofile_patientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_physiotherapist',
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='num_coleg',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='num_history',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
