# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 10:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160309_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='medicalprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patientprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='num_cole',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='num_hist',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
